"""initial migration

Revision ID: fce4c7d2f0f6
Revises: 
Create Date: 2017-06-07 13:19:58.722466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce4c7d2f0f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demand',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('address', sa.VARCHAR(length=20), nullable=True),
    sa.Column('channel', sa.INTEGER(), nullable=True),
    sa.Column('model', sa.VARCHAR(length=20), nullable=True),
    sa.Column('datetime', sa.DATETIME(), nullable=True),
    sa.Column('demand_min', sa.FLOAT(precision='20,2'), nullable=True),
    sa.Column('demand_quarter', sa.FLOAT(precision='20,2'), nullable=True),
    sa.Column('R_value', sa.FLOAT(precision='20,2'), nullable=True),
    sa.Column('S_value', sa.FLOAT(precision='20,2'), nullable=True),
    sa.Column('T_value', sa.FLOAT(precision='20,2'), nullable=True),
    sa.Column('Total_value', sa.FLOAT(precision='20,2'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('demand')
    # ### end Alembic commands ###
